### ISSUE TITLE
Tasks by Nov5 (W45)

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/PP2_CS_WS_2015-16#1]
- [x] Get access to original tool's svn repository
- [x] Move svn to git repository **preserving history** (this will be verified!)
- [x] **DO NOT MODIFY ANYTHING IN THE FILES BEFORE YOU VERIFY THE HISTORY IS PRESERVED**
- [x] Write in the correct authors email addresses in the git commits. [More info here](https://github.com/Rostlab/PP2_CS_WS_2015-16#documentation)
- [ ] Push code to respective GitHub repository
- [x] Prepare minimal `README.md` with some key points of the tool:
  - [ ] Development year (first commit)
  - [ ] Authors
  - [ ] Programming Language
  - [ ] Machine learning method(s) used / methodology used
  - ? Another tiny bit you may find interesting
- [x] Put your full name and a nice photo of you on your GitHub profile :-) _//that way is easier for me to identify who is who :)_
- [ ] Do a short ~10 min presentation of your progress so far and interesting findings you got

**Comment by juanmirocks** [comment]
Likely you can find more info of the tools yourselves.

_--> Beware of googling your packages and searching more info on the rostlab open wiki or PredictProtein.org_

**Comment by juanmirocks** [comment]
@Rostlab/pp2_cs_ws_2015-16-students please watch this repo and issue

**Comment by juanmirocks** [comment]
@Rostlab/pp2_cs_ws_2015-16-students by this Thursday Nov 5, we expect that every team will do a short 10 min presentation (see issue description). For the future, unless we say otherwise, we will always expect that you present your progress in the meetings. Either all teams in one session or split. -- We will review in due time if we need to meet every week.

The presentation format is informal but must be informative. You're free to prepare slides, other medium, or just show all your findings with the repo documentation itself (what I prefer)

**Comment by Startouf** [comment]
Hey sorry to be this late, but I'm not sure we have enough content for a 10 minutes presentation... The tasks were just to port the repositories to github and understand briefly what's happening inside each tool. Not sure we can spend more than 2 minutes on that (or was it 10mins for all the groups ?).

**Comment by juanmirocks** [comment]
10min really max. Describe key points of the tool. That's enough
