### ISSUE TITLE
Credentials for accessing SVN of RostLab

### ISSUE THREAD

**Issue by GrimSmiler** [Rostlab/PP2_CS_WS_2015-16#10]
Hi!

I haven't received an email with credentials for connecting with ssh to SVN repositories.
Whom should I ask for help?

Best Regards,
Ilya Migal

**Comment by rocreguant** [comment]
At the beginning of the course @jmcejuela sent us user & pass. He might do the same with you when he sees this

**Comment by GrimSmiler** [comment]
Thanks @rocreguant , I'll write him an email.

**Comment by juanmirocks** [comment]
@GrimSmiler yes. Though you won't need those credentials since the consurf repositories should be outside from our servers.

Thanks @rocreguant for your help !
