### ISSUE TITLE
[ConSurf] Credentials for ssh

### ISSUE THREAD

**Issue by GrimSmiler** [Rostlab/PP2_CS_WS_2015-16#11]
Hi @jmcejuela !

I have received an email from Guy (topic is "Protein Prediction 2 Ex. Source code problem"), that the version of the ConSurf I should be using is stored at:
file:///mnt/project/subversion/consurf/branches/consurf_1_0_0

But I cannot access it. Can Youhelp me with getting the credentials?\

**Comment by juanmirocks** [comment]
@GrimSmiler I already gave you the credentials.

Now waiting for our administrator to move the svn repo.

Please bug me if this doesn't happen soon enough.

Thanks for your patience ! :-)

In the meantime I would suggest you to read all the documentation you can find about ConSurf.

**Comment by GrimSmiler** [comment]
Found them! Thanks @jmcejuela 

Any news regarding the SVN?

**Comment by juanmirocks** [comment]
I wrote our administrator Tim again. Let's wait.

He is at the moment in Luxemburg.....

**Comment by GrimSmiler** [comment]
No problem.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1&source=email_footer_2] On пн, нояб. 30, 2015 at 11:34 AM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
I wrote our administrator Tim again. Let's wait.

He is at the moment in Luxemburg.....

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/PP2_CS_WS_2015-16/issues/11#issuecomment-160590838] .[https://github.com/notifications/beacon/AExpfSHMKgOq3XdQ8wI_UYG2PD7QRKnRks5pLB2igaJpZM4GlZc7.gif]

**Comment by juanmirocks** [comment]
He comes back on Wednesday or Thursday from Lux.

**Comment by GrimSmiler** [comment]
Ok, i'll try to read as much as i can on documentation and maybe start doing a
readme.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1&source=email_footer_2] On пн, нояб. 30, 2015 at 2:18 PM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
He comes back on Wednesday or Thursday from Lux.

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/PP2_CS_WS_2015-16/issues/11#issuecomment-160624653] .[https://github.com/notifications/beacon/AExpfdDHYHfhrT52k_UDnCNKs6R0JLU5ks5pLEQlgaJpZM4GlZc7.gif]

**Comment by juanmirocks** [comment]
I think it's resolved :-)

Thanks for coming today to tim's office :)

**Comment by GrimSmiler** [comment]
No problem))

Yeap. The issue is resolved now. On чт, дек. 03, 2015 at 2:05 PM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
I think it's resolved :-)

Thanks for coming today to tim's office :)

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/PP2_CS_WS_2015-16/issues/11#issuecomment-161631658] .[https://github.com/notifications/beacon/AExpfZfS9dHGOlfMuum18gQCsTkz-Klqks5pMDWygaJpZM4GlZc7.gif]
