### ISSUE TITLE
January 7th - What's up ?

### ISSUE THREAD

**Issue by Startouf** [Rostlab/PP2_CS_WS_2015-16#13]
Will there be an exercise session on the 7th January ?

**Comment by juanmirocks** [comment]
@Rostlab/pp2_cs_ws_2015-16-students **On January 7th there will be NO class.**

Likely, the latest presentations will take place on January 21st & 28th.

@Startouf thanks for pressing on this.

**Comment by juanmirocks** [comment]
@Rostlab/pp2_cs_ws_2015-16-students the final 2 presentations will take place on **Jan 21st** and **Feb 4** divided in 4 groups, same order as las time.

**Comment by GrimSmiler** [comment]
@jmcejuela , i am not sure i will be able to be there on 4th of feb.
can i present on 21st?

**Comment by juanmirocks** [comment]
@GrimSmiler in principle yes, let me write tomorrow the final schedule.

@Rostlab/pp2_cs_ws_2015-16-students please if anybody else has impossible dates, let us know soon.

**Comment by anapetrovska** [comment]
@GrimSmiler if @jmcejuela allows we can switch the dates, we have on 21st, but it will be much better for us to have it on 4th.

Thanks in advance!

**Comment by juanmirocks** [comment]
@Rostlab/pp2_cs_ws_2015-16-students presentations schedule:

January 21st:
- SNAP2 -- Linda & Andre
- LocTree (3) -- Sonja & Alejandro
- MetaDisorder -- Sirma & Irem
- ConSurf -- Ilya

Feb 4th:
- someNA -- Christian & Dimitri
- TMSEG -- Muriel & Cyril
- PROFsec -- Roc & Cristina
- MetaStudent -- Ansh & Ana & Manuel

Until now I hadn't reviewed all of the tools' documentation, but now I'm checking everything. Expect several issues created in your respective tools ;)
