### ISSUE TITLE
Do you guys need a mini introduction to git & GitHub ?

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/PP2_CS_WS_2015-16#2]
I'm happy to give a mini introduction if there is enough people interested.

Please write here a comment to ask for it! :)

**Comment by ccmoratilla** [comment]
I would be interested =)

**Comment by mmerustes** [comment]
Uffff...me too. I have tried by myself but I am a little bit lost :S

**Comment by juanmirocks** [comment]
@ccmoratilla @mmerustes hope you found it useful.

In general for all students, if you need an introduction to some concepts (specially ML or biology), just let us know.

(@mmerustes please have a photo on your profile :-)
