### ISSUE TITLE
svn repos cannot be accessed without a Rostlab account

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/PP2_CS_WS_2015-16#3]

**Comment by Startouf** [comment]
I actually couldn't find where the svn repositories were to begin with. I suppose the links are in one of those password protected pages like the internal wiki ?

**Comment by juanmirocks** [comment]
@Startouf very true. I couldn't find it myself yet either. The same applies for the tool `someNA`. I'm talking with our administrator to resolve this issue. In the meantime, please exhaustively try to search for the tool's code location. Perhaps by checking the PredictProtein.org service, other wiki pages, google, ...

So far I collected to the best of my findings the necessary repos here: https://github.com/Rostlab/PP2_CS_WS_2015-16/blob/master/README.md#tools

**Comment by juanmirocks** [comment]
Sorry for these initial hurdles. However, solving these hurdles for external uses is indeed the whole point.

Hope in the end we can have really useful tools for the scientific community.

**Comment by juanmirocks** [comment]
@Rostlab/pp2_cs_ws_2015-16-students Access should now be possible to the repos. See: https://github.com/Rostlab/PP2_CS_WS_2015-16/wiki/HOWTO-access-rostlab-svn-repos

For `TMSEG` and the other teams with caveats please let's keep the conversation in your specific repos.
