### ISSUE TITLE
Write internal documentation on the tool repo wiki

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/PP2_CS_WS_2015-16#4]
Awesome seeing already some first commits.

@Startouf & @mkeribin from [TMSEQ](https://github.com/Rostlab/TMSEG) had the great idea of documenting their weekly efforts and findings (in `.tex` files or whatever format you want). However, **your internal documentation must go to the tool github repo _wiki_ only**. The repo itself must be just for the tool's code.

This is a general announcement for all teams.

**Comment by Startouf** [comment]
Hmm It's not really clear. Did you mean the wiki on the rostlab website or the github wiki tab for each project ? Also we may have to write formulas in our documentation, and AFAIK GitHub doesn't support LaTex in its builtin wiki ?

**Comment by jmcejuela** [comment]
@Startouf very true. I couldn't find it myself yet either. The same applies for the tool `someNA`. I'm talking with our administrator to resolve this issue. In the meantime, please exhaustively try to search for the tool's code location. Perhaps by checking the PredictProtein.org service, other wiki pages, google, ...

So far I collected to the best of my findings the necessary repos here: https://github.com/Rostlab/PP2_CS_WS_2015-16/blob/master/README.md#tools

**Comment by juanmirocks** [comment]
@Startouf thanks. I mean the github wiki tab.

As for the `.tex` files. That is somewhat true. So far I see 2 solutions:
- (Github wikis are actually git repos themselves. You can clone them (in your case [this is the URL](https://github.com/Rostlab/TMSEG.wiki.git)) and push any file you want, including `.tex` files
- Write the `.tex` files in markdown within verbatim (`...`)

Besides, in markdown you can also write html. And AFAIK you can write some math formulas with some extensions. But I'm not familiar with it. You know more?

**Comment by juanmirocks** [comment]
Let me know if you have any other issue. Closing for now.
