### ISSUE TITLE
How to edit the Wiki?

### ISSUE THREAD

**Issue by rocreguant** [Rostlab/PP2_CS_WS_2015-16#5]
How to edit the Wiki ( https://rostlab.org/owiki/index.php/Packages )?
I've tried to login the user and password sent to us via email but it does not work.

**Comment by juanmirocks** [comment]
Good point. It seems you need a specific rostlab account to edit the "open wiki"...

Question: what do you want to edit, the links?

Write down (document) everything you want to update on the wiki. Then, later I do myself:
- either apply the changes on the owiki
- or just remove the info there and point to this repository exclusively (my preferred option) -- I want to get rid of the owiki ;)

**Comment by rocreguant** [comment]
ok ;)
For the moment no changes
