### ISSUE TITLE
Tasks by Nov19 & Nov26 (W47 & W48)

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/PP2_CS_WS_2015-16#7]
Great presentations today Nov 5. As you see in the [Exercise Work description](https://github.com/Rostlab/PP2_CS_WS_2015-16#work), we have already accomplished the first task of moving the repos. That's a great achievement by itself.

Next, you will concentrate on checking and improving the usability of the tools. We skip Nov 12 so that you have more time for this task. On Nov 19 we likely have 4 teams presenting for ~15-20min (the first on the list, namely: `SNAP2, LocTree, MetaDisorder, MetaStudent`). On Nov 26, 4 rest teams.

The specific sub-tasks are described in the Exercise Work description. They may be a bit general, but you should concentrate on main 3 points:
- [ ] Run or attempt to run the tools
- [ ] Document everything you find and specially document HOWTO install & HOWTO run the tools
- [ ] Create github issues with the problems you find along the way and also try to fix them

---

After this, we will likely have other mid-presentation where, after the main usability points are done, you will concentrate in really and deeply understanding the tools, theory behind, biology, machine learning, etc.

We may also have other days with very short progress descriptions as happened today Nov 5.

The final presentation should round up everything. You may present in front of Burkhard Rost. He will surely appreciate your efforts.

**Comment by juanmirocks** [comment]
Please for all your changes to the repo files, **use the git branching model of master & develop & features branches**. More info: http://nvie.com/posts/a-successful-git-branching-model/

A GUI like [SourceTree](https://www.sourcetreeapp.com/) or others, may simplify this process.

**Comment by juanmirocks** [comment]
@Rostlab/pp2_cs_ws_2015-16-students sorry guys for my silence in the  last days. I am currently in Japan and my laptop got broken. Hopefully I can answer u guys tomorrow Tuesday

**Comment by fsblu** [comment]
Hello,
Are we supposed to have another presentation tomorrow?
Sorry if that was asked before.

**Comment by lrrichter** [comment]
Please check at the top to which group you belong. Tomorrow present 4 groups and the other 4 groups present next week.

**Comment by juanmirocks** [comment]
Closing this task now. Please remember to keep documenting and creating github issues for your respective repos as soon as you find problems with your tools
