### ISSUE TITLE
update open wiki links

### ISSUE THREAD

**Issue by seitza** [Rostlab/PP2_CS_WS_2015-16#8]
In the (PP2_CS_WS_2015-16) Readme there is a task called
- Where is the code? obviously now in the respective GitHub repos. **Please update Rostlab's open wiki links**

As we do not have rights to access the Rostlab open wiki, will you ( @jmcejuela  ) do it, or will we get access?

**Comment by juanmirocks** [comment]
@seitza you're right. Currently the rostlab wiki is closed for external users.

Likely, you will provide all the needed & updated info on the github wikis and I will later update the rostlab wiki myself as needed.
