### ISSUE TITLE
install and execute with various OS

### ISSUE THREAD

**Issue by seitza** [Rostlab/PP2_CS_WS_2015-16#9]
On which OS should we test the methods?

You already pointed out:
- Mac OS X (10.10.)
- Debian 7 "wheezy" (install via apt-get)

anything else?

**Comment by juanmirocks** [comment]
Thanks for the question and sorry for the late reply.

First and foremost those OSes (note, hopefully it works with `OS X 10.11` that is El Capitan too)

But (OPTIONALLY) if you also can test on other environments such as Ubuntu, that would also be very helpful.
